version: '3.3'

services:
  cvat_opa:
    container_name: cvat_ima
    image: openpolicyagent/opa:0.34.2-rootless
    restart: always
    networks:
      - ima
    volumes:
      - ./cvat/apps/iam/rules:/rules
    ports:
      - '8181:8181'
    command: run --server --addr :8181 --set=decision_logs.console=true /rules

networks:
  ima: